#!/usr/bin/env bash
# Bash script that Install nginx on your web-01 server and requirements
apt-get update
apt-get install -y nginx
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        echo 'Hello World!' > index.html;
        return 200;
    }
}" > /etc/nginx/sites-available/default
# Restart Nginx
service nginx restart

# Ensure Nginx is running
if pgrep -x "nginx" > /dev/null
then
    echo "Nginx installed and configured successfully."
else
    echo "Error: Nginx is not running."
fi
